### ISSUE TITLE
福特 SYNC3.2 黑屏

### ISSUE THREAD

**Issue by nzlov** [puderty/pudev#1]
用官方版本正常投屏，但是用这个修改映射版中控黑屏。

## Android Version

```
Android 10
```

## Car

```
2017 蒙迪欧 HEV
```

## Car System

```
SYNC 3.2
```

**Comment by nzlov** [comment]
使用`CarlifeEx-5.5.1-r40`可以投屏，使用`模式1`电话形式可以播放音频

**Comment by nzlov** [comment]
是否是高清的问题？

**Comment by puderty** [comment]
奇怪，我是锐界也是3.2我中午试了可以的啊，你装的映射还是高清版？另外可以试试重启手机

**Comment by nzlov** [comment]
重启手机试过了，我看到手机上显示有缩放，但是底还不是黑的，而是程序界面。

**Comment by a359880271** [comment]
你好 ， 能分享给我一个映射最新版的下载地址嘛？

**Comment by wacoi** [comment]
楼主辛苦了，一连上车机，手机跟车机的显示都会缩小，能投屏成功，就是都缩小了，

**Comment by jhwooo** [comment]
Cx5,Nokia,   android10,也是黑屏

**Comment by puderty** [comment]
你们试试最新的那个呢？
