### ISSUE TITLE
关于车机无法全屏！

### ISSUE THREAD

**Issue by clean8** [puderty/pudev#13]
您好，请问可不可以让他在车机端全屏显示？目前手机屏幕多大 映射到车机就多大。

**Comment by puderty** [comment]
好像有部分车机是支持比例适配的，就是说强行把手机传过去的图像拉伸，但也是变形的。对于其他的车机，只能是等比放大缩小显示，跟家里高清电视看标清频道一回事。另外root的设备可以做到修改手机的分辨率来做到完美适配，但root的手机太少了不打算做

**Comment by clean8** [comment]
不知道可不可以满足我全屏显示。图像轻微出现拉伸 也是无所谓的。谢谢！

**Comment by puderty** [comment]
要root才能做到的。

**Comment by puderty** [comment]
试试最新版本，没有root的话看看说明。
