### ISSUE TITLE
首屏不能创建高德车机版的快捷方式

### ISSUE THREAD

**Issue by kocawin** [puderty/pudev#14]
能正常创建手机版高德快捷方式. 删除手机版后重启carpro 就只剩下微信了.

车机版这里下载https://auto.amap.com/download

**Comment by kocawin** [comment]
在删除手机版并重启carpro之前. 原快捷方式可以正常打开高德车机版.

**Comment by kocawin** [comment]
不删除手机版的话 通过首屏快捷方式打开还是手机版. 希望能优先使用车机版

**Comment by kocawin** [comment]
有需要直接启动高德的小伙伴们可以试试 takser这个软件 
比如可以设置usb已连接+carlife已经启动的时候自动启动高德地图

**Comment by puderty** [comment]
满足你这个小小的需求，去下最新的链接吧

**Comment by kocawin** [comment]
多谢
