### ISSUE TITLE
在Carlife的页面下，在车机屏幕上无法使用小米手机悬浮球功能。

### ISSUE THREAD

**Issue by lemontree111** [puderty/pudev#20]
我的手机是小米开发版系统，有root权限，可以实现车机上反控。
问题详细如下：
把小米手机连接上车机之后，当显示Carlife页面的时候，在车机屏幕上使用悬浮球功能都无效，当画面切换到手机其他页面，如主页/高德地图等页面之后悬浮球功能正常。
但是不管有没有连接上车机，在手机上的所有页面下的悬浮球功能都是正常的，

**Comment by puderty** [comment]
是的，因为在carlife界面的时候，事件都是丢给carlife处理，但carlife界面响应不了悬浮球的事件。这个问题可能不打算处理了

**Comment by lemontree111** [comment]
好的，其实也没有关系，因为已经有了退回手机桌面的快捷方式，已经很好的处理了这个问题，辛苦你了。
