### ISSUE TITLE
你好！我现在在想能不能实现音乐那块读取本地usb里面的音乐？

### ISSUE THREAD

**Issue by clean8** [puderty/pudev#21]
如果可以实现读取车机usb本地音乐那就太好了。还有关于那些地图和微信之类的第三方应用 可不可以实现在百度carlife里创建一个内置窗口打开。 我只是想法而已  不要见怪。并没有别的意思。 哦还有 百度carlife已经更新到了6.0.3测试版不知道有没有什么bug修复。

**Comment by puderty** [comment]
没办法。版本升级也不打算做了，一些小功能小优化，大家也不是冲着那些去的
