### ISSUE TITLE
发现个问题

### ISSUE THREAD

**Issue by clean8** [puderty/pudev#22]
我是长安车，手机是vivo 在车机上可以点击 但是在车机端用输入法 会返回到百度carlife主界面。未root

**Comment by puderty** [comment]
之前版本加的双击返回carlife导致的，今天只是测试版先试试能不能行，我也是刚才才在自己车上测试可行了。下周修正这个

**Comment by clean8** [comment]
> 之前版本加的双击返回carlife导致的，今天只是测试版先试试能不能行，我也是刚才才在自己车上测试可行了。下周修正这个

嗯嗯，不知道那个百度carlife只能读取手机音乐 而不能读取车机usb的音乐 不知道可否添加相关路径 来实现 在百度carlife下能读取手机本地音乐又能读取车机usb上的音乐呢？

**Comment by puderty** [comment]
这个应该没可能，你可以点返回车机图标返回车机播放音乐再返回啊

**Comment by clean8** [comment]
这个我试过 返回到车机播放音乐后 再返回百度carlife 车机的音乐就停止了。所以我才想问问这个功能可不可以实现。

**Comment by clean8** [comment]
我感觉大神目前应该做做精简操作，去掉不常用的功能 留有基本功能 应该会流畅许多。目前感觉手机和车机有操作上的延时。就慢个1秒。其实感觉用百度carlife里的功能都是次要的 主要是能投屏 用手机上的app。望采纳。谢谢！
