### ISSUE TITLE
安卓全是全面屏手机，投屏后严重黑边

### ISSUE THREAD

**Issue by yezi0746** [puderty/pudev#23]
大师你好  现在安卓全是全面屏手机，投屏后严重黑边，能否添加一个投屏输出选项比如16:9 ，匹配一些主流的车机屏幕。投屏主要目的是投别的APP到车机，是否能去掉 carlife界面，链接车机后直接显示手机桌面到车机。之前收藏过2个修改过的carlife版本，给大师你看看。一个无界面，高版本安卓无法使用适用于安卓6.0。一个是精简版的。我用老款手机能正常使用。网盘链接: https://pan.baidu.com/s/1DsuABMBt9WpbuYzyO0l3hQ 提取码: aqsv

**Comment by puderty** [comment]
建议你更换跟你车机屏幕同等比例的手机。至于默认投屏桌面，你可以连上后点击carlife里的返回桌面图标。
