### ISSUE TITLE
每次连接车机的时候都会显示“百度CarPro将开始截取您的屏幕上显示的所有内容。”

### ISSUE THREAD

**Issue by lemontree111** [puderty/pudev#24]
大师你好，
我的手机每次连接车机的时候都会显示“百度CarPro将开始截取您的屏幕上显示的所有内容。”
下面只有“取消“和“立即开始的按钮”。请问能否增加勾选始终允许的选项？避免每次都需要点击立即开始，谢谢！
![屏幕显示的内容](https://user-images.githubusercontent.com/57693510/69034416-2091a780-0a1c-11ea-8d9f-303ce969a00e.png)

**Comment by puderty** [comment]
这是你手机系统的问题，安全限制比较严格也没办法，厂商觉得这样更安全

**Comment by lemontree111** [comment]
> 这是你手机系统的问题，安全限制比较严格也没办法，厂商觉得这样更安全

好的，谢谢你

**Comment by lemontree111** [comment]
那是我手机上的bug,实际上点击左边的空白处能打上勾，没有显示而已，今天早上试了，问题已经解决了。还是谢谢你的回复。
