### ISSUE TITLE
精简建议（同感来自网友clean8）

### ISSUE THREAD

**Issue by zyf364** [puderty/pudev#26]
我感觉大神目前应该做做精简操作，去掉不常用的功能 留有基本功能， 应该会流畅许多。目前感觉手机和车机有操作上的延时。就慢个1秒。其实感觉用百度carlife里的功能都是次要的 主要是能投屏 用手机上的app。望采纳。谢谢！

**Comment by puderty** [comment]
能用就行了，删了功能也不可能更快了，投屏的机制就是这样。功能没太大问题这就是终版了
